### PR TITLE
fix: `instanceof` checks

### LINKED ISSUE #787: fix: `instanceof` checks for custom classes
These may break when code is bundled and should be circumvented.

### PR DESCRIPTION
**Pull request by kaljarv**
## WHY:

Fixes #787 

Convert all istanceof checks used for custom classed defined in the
packages to use proprietary type guard utilities.

Instanceof does not work reliably across packages due to name changes
in bundling.

## Check off each of the following tasks as they are completed

- [x] I have reviewed the changes myself in this PR. Please check the [self-review document](https://github.com/OpenVAA/voting-advice-application/blob/main/docs/contributing/self-review.md)
- [x] I have added or edited unit tests.
- [x] I have run the unit tests successfully.
- [ ] I have run the e2e tests successfully.
- [ ] I have tested this change on my own device.
- [ ] I have tested this change on other devices (Using Browserstack is recommended).
- [ ] I have tested my changes using the [WAVE extension](https://wave.webaim.org/extension/)
- [ ] I have tested my changes using keyboard navigation and screen-reading
- [ ] I have added documentation where necessary.
- [x] Is there an existing issue linked to this PR?
- [ ] I have cleaned up the commit history and checked the commits follow [the guidelines](https://github.com/OpenVAA/voting-advice-application/blob/main/docs/contributing/CONTRIBUTING.md#commit-your-update)

### CODE REVIEW

File: packages/data/src/utils/typeGuards.ts
Comment (kaljarv) [inline packages/data/src/utils/typeGuards.ts:1]: This format of type guards is now used for the submodules.

File: frontend/src/lib/components/entityFilters/EntityFilters.svelte [hunk 1]
```diff
@@ -16,15 +16,26 @@ Show filters for entities. This component and the individual filter components o
...
 
   export let filterGroup: $$Props['filterGroup'];
   export let targets: $$Props['targets'];
+
+  const { t } = getComponentContext();
+
+  /** Type params cannot be used in the HTML part */
+  function _isEnumeratedFilter(filter: unknown) {
+    // TODO[Svelte 5]: Check if needed
+    return isEnumeratedFilter<MaybeWrappedEntityVariant, AnyEntityVariant>(filter);
```
Comment (kaljarv) [inline frontend/src/lib/components/entityFilters/EntityFilters.svelte:37]: Here we need to specify the type params so that `<EnumeratedEntityFilter>` accepts the filters. Note that types and type params cannot be used in the HTML part, hence the wrapper.
